# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: SynopsysSecurityScan@1
  inputs:
    scanType: 'polaris'
    bridge_polaris_application_name: 'JWtest'
    bridge_polaris_project_name: 'HelloJava'
    bridge_polaris_assessment_types: 'sca'
    bridge_polaris_branch_name: 'main'
    polarisPRCommentEnabled: true
    polarisReportsSarifCreate: true

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
