# example ADO pipeline for Polaris using the Bridge CLI
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: BRIDGE_POLARIS_APPLICATION_NAME
  value: 'JW-Hello-$(Build.Repository.Name)'
- name: BRIDGE_POLARIS_PROJECT_NAME
  value: 'JW-$(Build.Repository.Name)'
steps:  
- task: SSH@0
  inputs:
    sshEndpoint: 'SSHagent'
    runOptions: 'commands'
    commands: |
      echo "realizando un test"
      cd /opt
      curl -fLsS -o bridge.zip $BRIDGECLI_LINUX64 && unzip -qo -d $(Agent.TempDirectory) bridge.zip && rm -f bridge.zip
                $(Agent.TempDirectory)/synopsys-bridge --stage polaris polaris.assessment.types=SAST,SCA
    readyTimeout: '20000'
  displayName: 'Polaris Scan'
  env:
    BRIDGE_POLARIS_ACCESSTOKEN: $(BRIDGE_POLARIS_ACCESSTOKEN)
