name: CI-Polaris-Basic 
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: NEW Polaris Scan 1
        uses: synopsys-sig/synopsys-action@v1.9.0
        with:
          ### SCANNING: Required fields
          polaris_server_url: ${{ secrets.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_assessment_types: "SCA,SAST"
          polaris_application_name: "JWtest"
          polaris_project_name: "HelloJava"
              
         
          ### PULL REQUEST COMMENTS: Uncomment below to enable
          #polaris_prComment_enabled: ${{ github.event_name == 'pull_request' && 'true' || 'false' }}
          github_token: ${{ secrets.GIT_PAT }} # Required when PR comments is enabled
          #polaris_reports_sarif_create: ${{ github.event_name != 'pull_request' && 'true' || 'false' }}
          polaris_reports_sarif_severities: "CRITICAL,HIGH,MEDIUM,LOW"
          polaris_reports_sarif_groupSCAIssues: true
          polaris_reports_sarif_create: true
          polaris_upload_sarif_report: true
          polaris_reports_sarif_issue_types: 'SCA, SAST' 
          # polaris_upload_sarif_report: ${{ github.event_name != 'pull_request' && 'true' || 'false' }}
        

      #- name: Save Logs
       # if: always()
       # uses: actions/upload-artifact@v3
       # with:
        # name: bridge-logs
         #path: ${{ github.workspace }}/.bridge/**/*.json
          
