name: CI-Polaris-Basic 
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: microsoft
          cache: maven
      - name: NEW Polaris Scan 1
        uses: synopsys-sig/synopsys-action@v1.8.0
        with:
          ### SCANNING: Required fields
          polaris_server_url: ${{ secrets.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_assessment_types: "SCA,SAST"
          polaris_application_name: "JWtest"
          polaris_project_name: "HelloJava"
          polaris_branch_name: "main"
          
         
          ### PULL REQUEST COMMENTS: Uncomment below to enable
          # polaris_prComment_enabled: ${{ github.event_name == 'pull_request' && 'true' || 'false' }}
          #polaris_prComment_enabled: true 
          #github_token: ${{ secrets.git_pat }} # Required when PR comments is enabled

      #- name: Save Logs
       # if: always()
       # uses: actions/upload-artifact@v3
       # with:
        # name: bridge-logs
         #path: ${{ github.workspace }}/.bridge/**/*.json
          
